platform :ios, '6.0'

target 'BTNSDateFormatterFactoryDemo' do
  use_frameworks!

  pod 'BTNSDateFormatterFactory', '0.1.1'

  target 'BTNSDateFormatterFactoryDemoTests' do
    inherit! :search_paths

  end

end
