platform :ios, '6.0'

target 'BTNSDateFormatterFactoryDemo' do
  use_frameworks!

  pod 'BTNSDateFormatterFactory', 'v0.1.0'

  target 'BTNSDateFormatterFactoryDemoTests' do
    inherit! :search_paths

  end

end
